services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  authservice:
    build: ./authservice
    ports:
      - "9000:9000"

  userservice:
    build: ./service3
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq

  messageservice:
    build: ./service2
    ports:
      - "8082:8082"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq

  bff:
    build: ./bff
    ports:
      - "8080:8080"
    depends_on:
      - authservice
      - userservice
      - messageservice
    environment:
      SERVICES_AUTH_URL: http://authservice:9000
      SERVICES_USER_URL: http://userservice:8083
      SERVICES_MESSAGE_URL: http://messageservice:8082