apiVersion: apps/v1
kind: Deployment
metadata:
  name: messageservice
spec:
  selector:
    matchLabels:
      app: messageservice
  template:
    metadata:
      labels:
        app: messageservice
    spec:
      containers:
        - name: messageservice
          image: microservices_lab2-messageservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/message_db?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: com.mysql.cj.jdbc.Driver
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: org.hibernate.dialect.MySQLDialect
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: GRPC_CLIENT_USERSERVICE_ADDRESS
              value: userservice:8083
---
apiVersion: v1
kind: Service
metadata:
  name: messageservice
spec:
  selector:
    app: messageservice
  ports:
    - port: 8082
      targetPort: 8082