spring.application.name=bff
server.port=8080

jwt.secret=myVeryLongSecretKeyForSigningJWTs2024!

services.auth-url=http://localhost:9000
services.user-url=http://localhost:8083
services.message-url=http://localhost:8085